# Generated by Django 4.1.3 on 2022-12-10 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-pubdate',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-pubdate',)},
        ),
        migrations.AddField(
            model_name='comment',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='pubdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
