# Generated by Django 4.1.3 on 2022-12-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_field',
            field=models.ImageField(blank=True, null=True, upload_to='post_images'),
        ),
    ]
